### ISSUE TITLE
Extra Credit Feature Suggestion

### ISSUE THREAD

**Issue by EB30** [du00d/EasySchedule#1]
I suggest to add "extra credit feature" s.t. those with applicable extra credits from AP, IB, A-Level courses can have an optimized schedule planner rather than one that starts with 0 credits.

**Comment by pohaoc** [comment]
regular credits are actually implemented but not displayed in the GUI because I figured the main purpose of the program is to visualize the gen ed credit and using it as a tool to help plan your classes. If you want to enable it simply go in to the parser class and return the credit field. Thanks for the note!
